config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:create, :show]
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # つけるとバッチが動かない
  # has_many :items, dependent: :destroy


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_data

  def index
    # 10件ずつ扱う
    @items = Item.all.each_slice(10)
  end

  def create
    # バッチ　リロードしたらすぐ保存

    # all_itemsで上位10件を取得
    @all_items.first(10).each do |a, b, c, d, e, f, g|
      # p g
      Item.create(title: a, url: b, lgtm: c, user_name: e, posted_at: d, tag: f, qiita_id: g)
      # すでにユーザーが存在していたらItemのみを保存する
      unless User.exists?(qiita_id: g)
        User.create(qiita_id: g, name: e)
      end
    end
    redirect_back(fallback_location: root_path)
  end

  def show
    @first = params[:id].to_i
    # 10件を取得
    @items = Item.where(id: @first..(@first+9))
    @items_first = Item.find(@first)
  end

  private
    def get_data
      require 'net/http'
      require 'open-uri'

      today = Date.today
      # 1週間前の日付を取得
      params_date = (today - 7).strftime

      # アクセストークン環境変数化
      access_token = ENV['access_token']
      headers = {'Authorization' => "Bearer #{access_token}"}

      # pageを回して配列でデータを取得
      result = []
      i = 1
      while i <= 100 do
        uri = URI.parse("https://qiita.com/api/v2/items?page=#{i}&per_page=100&query=created:>#{params_date}")
        res = URI.open(uri, headers)
        result << JSON.parse(res.read)
        i += 1
      end
      # p result

      # items[]に全てのデータを格納
      items = []
      # binding.irb

      # .mapで配列を生成し、そこに入れていく記述に修正
      # results = []
      # results.map {|result|　値}
      for f in 0..(result[0].size-1) do
        for val in result do
          if val[f]
            title = val[f]["title"]
            url = val[f]["url"]
            lgtm = val[f]["likes_count"]
            created_at = val[f]["created_at"]
            name = val[f]["user"]["name"]
            tag = val[f]["tags"]
            id = val[f]["user"]["id"]
              tag_names= []
              # each文で回して取得する
              tag.each { |t|
                tag_name = t["name"]
                tag_names.append(tag_name)
              }
            items.append(title,url,lgtm,created_at,name,tag_names,id)
          end
        end
      end
        # itemsから1セット（7つのデータ）ずつ切り分けて格納
        set_items = items.each_slice(7).to_a
        # 要素3つ目(lgtm数で並び替え)
        set_items.sort_by! { |a| a[2] }
        # lgtm数の多い順に表示
        @liked_all_items = set_items.reverse

        # ページネーション
        @all_items = Kaminari.paginate_array(@liked_all_items).page(params[:page]).per(10)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    # @ranking = Item.find_by(User.group(:qiita_id).order('count(qiita_id) desc').pluck(:qiita_id))
    # p @ranking
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="container">
  <p><b>集計期間 : <%= (Date.today-7).strftime("%Y年%-m月%-d日") %> 0時0分から<%= Time.now.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒") %>まで</b></p>
    <div class="row justify-content-center", style="background-color:#eee;">
      <div class="col-md-2", style="padding:20px 0 20px 10px;">
        <%= link_to('リロード', 'javascript:void(0);', onclick: "window.location.reload();", class: "btn btn-danger")  %>
        <br><br>
        <%= form_with model: [Item.new, User.new], url: items_path, method: :post, local:true do |f| %>
          <%#= f.hidden_field :title, value: "タイトル" %>
          <%= f.submit "上位10件のデータを保存", onclick: "window.location.reload();", class: "btn btn-outline-dark" %>
        <% end %>

        <h5>バックナンバー一覧<br>(※取得日)</h5>
        <% @items.each do |item| %>
          <%#= item[0].id %>
        <p><%= link_to "#{item[0].created_at.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒")}", item_path(item[0].id) %></p>
        <% end %>
      </div>

      <div class="col-md-10", style="background-color:white; border:1px solid #eee;">
        <% @all_items.each do |i| %>
          <h2><span class="lgtm"><%= i[2] %></span>
          <%= link_to "#{i[0]}", "#{i[1]}", target: :_blank, rel: "noopener noreferrer" %></h2>

          <div class="item_text">
            <div style="text-align:right;">
              <% i[5].each do |tag| %>
                <button type="button" class="btn-tag" disabled><%= tag %></button>
              <% end %>
            </div>
            created_at : <%= i[3].to_datetime.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒") %><br>
            name : <%= i[4] %> <span style="color: #666;"><%= "@#{i[6]}" %></span>
          </div>

        <% end %>
      </div>
    </div>

    <div class="row justify-content-center", style="background-color: #eee; padding-top:15px;">
      <div class="col-md-3 col-md-offset-3">
        <%= paginate @all_items, theme: 'bootstrap-5' %>
      </div>
    </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <h2>バックナンバー(上位10件）</h2>
  <div class="row justify-content-center", style="background-color:#eee;">
  <div class="col-md-10", style="background-color:white; border:1px solid #eee;">
      <h3>集計期間：
        <%= (@items_first.created_at.to_date-7).strftime("%Y年%-m月%-d日") %>0時0分0秒から
        <%= @items_first.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒") %></h3>

      <% @items.each do |f| %>
        <h2><span class="lgtm"><%= f.lgtm %></span>
        <%= link_to "#{f.title}", f.url, target: :_blank, rel: "noopener noreferrer" %></h2>
        <div class="item_text">
          created_at : <%= f.posted_at.strftime("%Y年%-m月%-d日 %-H時%-M分%-S秒") %><br>
          name : <%= f.user_name %> <span style="color: #666;"><%= "@#{f.qiita_id}" %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QiitaRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Qiita記事 リアルタイムLGTM数週間ランキング</h1>
    </header>
    <%= yield %>

    <footer>©️Qiitarticle</footer>
  </body>
</html>

app/views/users/index.html.erb
<% @users.uniq.each do |f| %>
  <div>
    <%= f.qiita_id %>のランキングに入った数は<%= Item.where(qiita_id: f.qiita_id).count %>
  </div>
<% end %>